# Generated by Django 4.2.5 on 2023-09-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='duration',
            field=models.TextField(default='0:00:00'),
            preserve_default=False,
        ),
    ]
