# Generated by Django 4.2.5 on 2023-09-29 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityTrackerApp', '0002_timelog_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
