# Generated by Django 4.2.5 on 2023-09-29 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityTrackerApp', '0003_alter_timelog_end_time_alter_timelog_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 16, 18, 18, 676521, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 16, 18, 18, 676506, tzinfo=datetime.timezone.utc)),
        ),
    ]
